# .goreleaser.yml
project_name: wallet-tracker
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "wallet-tracker"
    dir: .
    main: ./cmd/wallet-tracker
