version: '3.8'

services:
  neo4j:
    image: neo4j:4.4.0
    restart: unless-stopped
    container_name: wallet-tracker-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./data/neo4j:/data
    
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: wallet-tracker-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
